download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-nxos-9.0.0.tar.gz
format_version: 1.0.0
name: nxos
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 9.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/nxos/versions/9.0.0/
