---
- name: Configure Banner on NX-OS Switches
  hosts: nxos
  gather_facts: no
  tasks:
    - name: Check current MOTD banner
      nxos_command:
        commands:
          - show banner motd
      register: current_motd_banner
      ignore_errors: yes

    - name: Set MOTD banner on NX-OS Switches
      nxos_banner:
        banner: motd
        text: |
          *************************************************
          ***          Authorized access only!          ***
          ***            - - - - - - - - - -            ***
          ***    MOTD Banner Configured with Ansible    ***
          *************************************************
        state: present
      when: 
        - current_motd_banner is defined
        - current_motd_banner.stdout[0] is defined
        - current_motd_banner.stdout[0].find("Authorized access only!") == -1

    - name: Check current exec banner
      nxos_command:
        commands:
          - show banner exec
      register: current_exec_banner
      ignore_errors: yes

    - name: Set exec banner on NX-OS Switches
      nxos_banner:
        banner: exec
        text: |
          *************************************************
          ***           Welcome to NX-OS CLI            ***
          ***          Authorized access only           ***
          ***    Exec Banner Configured with Ansible    ***
          *************************************************
        state: present
      when: 
        - current_exec_banner is defined
        - current_exec_banner.stdout[0] is defined
        - current_exec_banner.stdout[0].find("Welcome to NX-OS CLI") == -1
