---
- name: NXOS VDC configuration
  hosts: nxos
  gather_facts: false
  pre_tasks:
    - name: Load configuration file
      ansible.builtin.include_vars:
        file: "{{ nxos_configuration_file }}"
  tasks:
    - name: Configure VDCs
      cisco.nxos.nxos_vdc:
        aggregate: "{{ nxos_vdc }}"
