---
- name: Gather facts
  hosts: nxos
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ecdsa
  connection: network_cli
  tasks:
    - name: Gather all facts
      cisco.nxos.nxos_facts:
        gather_subset: all
      register: nxos_facts

    - name: DEBUG | show all gathered facts
      ansible.builtin.debug:
        var: nxos_facts
