---
- name: Remove VDCs, VRFs, and VLANs on NX-OS Switches
  hosts: nxos
  gather_facts: false
  vars_files:
    - vars/nxos_config.yaml
  tasks:
    - name: Remove specified VDCs
      cisco.nxos.nxos_vdc:
        aggregate: "{{ nxos_vdc }}"
        state: absent

    - name: Remove specified VRFs
      cisco.nxos.nxos_vrf:
        aggregate: "{{ nxos_vrf }}"
        state: absent

    - name: Remove specified VLANs
      cisco.nxos.nxos_vlan:
        aggregate: "{{ nxos_vlans }}"
        state: absent
